name: Set up Minikube Cluster

on:
  pull_request:
    branches:
      - main

jobs:
  setup-minikube-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.4.0
        with:
          minikube-version: 'latest'
          kubernetes-version: 'latest'
          driver: docker

      - name: Start Minikube
        run: minikube start --wait=true

      - name: Verify Minikube Cluster
        run: |
          kubectl get nodes
          kubectl version
