name: Set up Minikube Cluster

on:
  push:
    branches:
      - main

jobs:
  setup-minikube-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          minikube-version: 'latest'
          kubernetes-version: 'latest'
          driver: docker

      - name: Start Minikube
        run: minikube start --wait=true

      - name: Verify Minikube Cluster
        run: |
          start_time=$(date +%s)
          minikube start --wait=true
          end_time=$(date +%s)
          echo "Spin-up time: $(($end_time - $start_time)) seconds"
          kubectl get nodes
          kubectl version